# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	desc "Versioning... "
	lane :version do		
		# build = get_build_number_from_plist
		# increment_build_number_in_plist(build_number: build.to_s)
		
	end



	desc "Push a new Development build to the Firebase Hosting"
	lane :develop do 		
		increment_build_number_in_plist
	end

	desc "Push a new Distribution build to the Firebase Beta"
	lane :beta do 
		increment_build_number_in_plist

	end

	desc "Push a new release build to the App Store"
	lane :release do 
		increment_build_number_in_plist
		
	end


end
